set_property PACKAGE_PIN K1 [get_ports {amplitude[0]}]
set_property PACKAGE_PIN F6 [get_ports {amplitude[1]}]
set_property PACKAGE_PIN J2 [get_ports {amplitude[2]}]
set_property PACKAGE_PIN G6 [get_ports {amplitude[3]}]
set_property PACKAGE_PIN H4 [get_ports {amplitude[4]}]
set_property PACKAGE_PIN H1 [get_ports {amplitude[5]}]
set_property PACKAGE_PIN G1 [get_ports {amplitude[6]}]
set_property PACKAGE_PIN G3 [get_ports amplitude_valid]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN N17 [get_ports rst]
set_property PACKAGE_PIN J5 [get_ports m_clk]
set_property PACKAGE_PIN H5 [get_ports m_data]
set_property PACKAGE_PIN F3 [get_ports m_clk_en]
set_property IOSTANDARD LVCMOS33 [get_ports {amplitude[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {amplitude[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {amplitude[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {amplitude[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {amplitude[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {amplitude[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {amplitude[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports amplitude_valid]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports m_clk]
set_property IOSTANDARD LVCMOS33 [get_ports m_clk_en]
set_property IOSTANDARD LVCMOS33 [get_ports m_data]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN F5 [get_ports lr_sel]
set_property IOSTANDARD LVCMOS33 [get_ports lr_sel]

set_property MARK_DEBUG true [get_nets m_clk_OBUF]

set_property MARK_DEBUG true [get_nets m_clk_en_OBUF]
set_property MARK_DEBUG true [get_nets amplitude_valid_OBUF]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

connect_debug_port u_ila_0/probe0 [get_nets [list {sample_counter_debug[0]} {sample_counter_debug[1]} {sample_counter_debug[2]} {sample_counter_debug[3]} {sample_counter_debug[4]} {sample_counter_debug[5]} {sample_counter_debug[6]} {sample_counter_debug[7]}]]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {counter_debug[0]} {counter_debug[1]} {counter_debug[2]} {counter_debug[3]} {counter_debug[4]} {counter_debug[5]} {counter_debug[6]} {counter_debug[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {counter_debug2[0]} {counter_debug2[1]} {counter_debug2[2]} {counter_debug2[3]} {counter_debug2[4]} {counter_debug2[5]} {counter_debug2[6]} {counter_debug2[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {sample_counter_debug[0]} {sample_counter_debug[1]} {sample_counter_debug[2]} {sample_counter_debug[3]} {sample_counter_debug[4]} {sample_counter_debug[5]} {sample_counter_debug[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 7 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {sample_counter_debug2[0]} {sample_counter_debug2[1]} {sample_counter_debug2[2]} {sample_counter_debug2[3]} {sample_counter_debug2[4]} {sample_counter_debug2[5]} {sample_counter_debug2[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list amplitude_valid_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list m_clk_en_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list m_clk_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
