set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports {first_data[0]}]
set_property PACKAGE_PIN K15 [get_ports {first_data[1]}]
set_property PACKAGE_PIN J13 [get_ports {first_data[2]}]
set_property PACKAGE_PIN N14 [get_ports {first_data[3]}]
set_property PACKAGE_PIN R18 [get_ports {first_data[4]}]
set_property PACKAGE_PIN V17 [get_ports {first_data[5]}]
set_property PACKAGE_PIN U17 [get_ports {first_data[6]}]
set_property PACKAGE_PIN U16 [get_ports {first_data[7]}]
set_property PACKAGE_PIN V16 [get_ports {last_data[0]}]
set_property PACKAGE_PIN T15 [get_ports {last_data[1]}]
set_property PACKAGE_PIN U14 [get_ports {last_data[2]}]
set_property PACKAGE_PIN T16 [get_ports {last_data[3]}]
set_property PACKAGE_PIN V15 [get_ports {last_data[4]}]
set_property PACKAGE_PIN V14 [get_ports {last_data[5]}]
set_property PACKAGE_PIN V12 [get_ports {last_data[6]}]
set_property PACKAGE_PIN V11 [get_ports {last_data[7]}]
set_property PACKAGE_PIN E18 [get_ports esp_rst]
set_property PACKAGE_PIN V10 [get_ports rst_i]
set_property PULLTYPE PULLUP [get_ports sda_master]
set_property PULLTYPE PULLUP [get_ports sda_slave]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {last_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports dmc_start_switch]
set_property IOSTANDARD LVCMOS33 [get_ports esp_rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports scl_master]
set_property IOSTANDARD LVCMOS33 [get_ports scl_slave]
set_property IOSTANDARD LVCMOS33 [get_ports sda_master]
set_property IOSTANDARD LVCMOS33 [get_ports sda_slave]

set_property PACKAGE_PIN D14 [get_ports i2c_slave_valid_o]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_slave_valid_o]

set_property PACKAGE_PIN F16 [get_ports lcd_start_o]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_start_o]

set_property PACKAGE_PIN G16 [get_ports mlp_start_o]
set_property IOSTANDARD LVCMOS33 [get_ports mlp_start_o]


set_property PACKAGE_PIN H14 [get_ports mlp_start_o_a]
set_property IOSTANDARD LVCMOS33 [get_ports mlp_start_o_a]

set_property PACKAGE_PIN D14 [get_ports boot_done]
set_property PACKAGE_PIN F16 [get_ports boot_valid]
set_property PACKAGE_PIN G1 [get_ports mlp_ready_o]
set_property IOSTANDARD LVCMOS33 [get_ports boot_done]
set_property IOSTANDARD LVCMOS33 [get_ports boot_valid]
set_property IOSTANDARD LVCMOS33 [get_ports mlp_ready_o]


set_property PACKAGE_PIN U11 [get_ports dmc_start_switch]

set_property PACKAGE_PIN F3 [get_ports sda_slave]
set_property PACKAGE_PIN J2 [get_ports scl_master]
set_property PACKAGE_PIN G6 [get_ports sda_master]

set_property PACKAGE_PIN V11 [get_ports {led[15]}]
set_property PACKAGE_PIN V12 [get_ports {led[14]}]
set_property PACKAGE_PIN V14 [get_ports {led[13]}]
set_property PACKAGE_PIN V15 [get_ports {led[12]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]


set_property PACKAGE_PIN H4 [get_ports mlp_busy_out]
set_property IOSTANDARD LVCMOS33 [get_ports mlp_busy_out]

set_property PACKAGE_PIN H1 [get_ports mlp_start_out]
set_property IOSTANDARD LVCMOS33 [get_ports mlp_start_out]

set_property IOSTANDARD LVCMOS33 [get_ports {dcm_state_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dcm_state_out[0]}]
set_property PACKAGE_PIN K15 [get_ports {dcm_state_out[1]}]
set_property PACKAGE_PIN H17 [get_ports {dcm_state_out[0]}]

set_property PACKAGE_PIN U13 [get_ports {AN_X_Display[7]}]
set_property PACKAGE_PIN K2 [get_ports {AN_X_Display[6]}]
set_property PACKAGE_PIN T14 [get_ports {AN_X_Display[5]}]
set_property PACKAGE_PIN P14 [get_ports {AN_X_Display[4]}]
set_property PACKAGE_PIN J14 [get_ports {AN_X_Display[3]}]
set_property PACKAGE_PIN T9 [get_ports {AN_X_Display[2]}]
set_property PACKAGE_PIN J18 [get_ports {AN_X_Display[1]}]
set_property PACKAGE_PIN J17 [get_ports {AN_X_Display[0]}]
set_property PACKAGE_PIN T10 [get_ports {CX_Display[7]}]
set_property PACKAGE_PIN R10 [get_ports {CX_Display[6]}]
set_property PACKAGE_PIN K16 [get_ports {CX_Display[5]}]
set_property PACKAGE_PIN K13 [get_ports {CX_Display[4]}]
set_property PACKAGE_PIN P15 [get_ports {CX_Display[3]}]
set_property PACKAGE_PIN T11 [get_ports {CX_Display[2]}]
set_property PACKAGE_PIN L18 [get_ports {CX_Display[1]}]
set_property PACKAGE_PIN H15 [get_ports {CX_Display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_X_Display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CX_Display[0]}]

set_property PACKAGE_PIN U12 [get_ports {select_seven[1]}]
set_property PACKAGE_PIN H6 [get_ports {select_seven[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_seven[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_seven[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_seven[0]}]
set_property PACKAGE_PIN T13 [get_ports {switch_seven[11]}]
set_property PACKAGE_PIN R16 [get_ports {switch_seven[10]}]
set_property PACKAGE_PIN U8 [get_ports {switch_seven[9]}]
set_property PACKAGE_PIN T8 [get_ports {switch_seven[8]}]
set_property PACKAGE_PIN R13 [get_ports {switch_seven[7]}]
set_property PACKAGE_PIN U18 [get_ports {switch_seven[6]}]
set_property PACKAGE_PIN T18 [get_ports {switch_seven[5]}]
set_property PACKAGE_PIN R17 [get_ports {switch_seven[4]}]
set_property PACKAGE_PIN R15 [get_ports {switch_seven[3]}]
set_property PACKAGE_PIN M13 [get_ports {switch_seven[2]}]
set_property PACKAGE_PIN L16 [get_ports {switch_seven[1]}]
set_property PACKAGE_PIN J15 [get_ports {switch_seven[0]}]



set_property PACKAGE_PIN G2 [get_ports scl_slave]

