set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports mic_data_valid]
set_property IOSTANDARD LVCMOS33 [get_ports M_LRSEL]
set_property IOSTANDARD LVCMOS33 [get_ports M_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports M_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN J5 [get_ports M_CLK]
set_property PACKAGE_PIN H5 [get_ports M_DATA]
set_property PACKAGE_PIN N17 [get_ports rst]
set_property PACKAGE_PIN F5 [get_ports M_LRSEL]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property PACKAGE_PIN C17 [get_ports {mic_data[31]}]
set_property PACKAGE_PIN D18 [get_ports {mic_data[30]}]
set_property PACKAGE_PIN E18 [get_ports {mic_data[29]}]
set_property PACKAGE_PIN G17 [get_ports {mic_data[28]}]
set_property PACKAGE_PIN D17 [get_ports {mic_data[27]}]
set_property PACKAGE_PIN E17 [get_ports {mic_data[26]}]
set_property PACKAGE_PIN F18 [get_ports {mic_data[25]}]
set_property PACKAGE_PIN G18 [get_ports {mic_data[24]}]
set_property PACKAGE_PIN D14 [get_ports {mic_data[23]}]
set_property PACKAGE_PIN F16 [get_ports {mic_data[22]}]
set_property PACKAGE_PIN G16 [get_ports {mic_data[21]}]
set_property PACKAGE_PIN H14 [get_ports {mic_data[20]}]
set_property PACKAGE_PIN E16 [get_ports {mic_data[19]}]
set_property PACKAGE_PIN F13 [get_ports {mic_data[18]}]
set_property PACKAGE_PIN G13 [get_ports {mic_data[17]}]
set_property PACKAGE_PIN H16 [get_ports {mic_data[16]}]
set_property PACKAGE_PIN K1 [get_ports {mic_data[15]}]
set_property PACKAGE_PIN F6 [get_ports {mic_data[14]}]
set_property PACKAGE_PIN J2 [get_ports {mic_data[13]}]
set_property PACKAGE_PIN G6 [get_ports {mic_data[12]}]
set_property PACKAGE_PIN E7 [get_ports {mic_data[11]}]
set_property PACKAGE_PIN J3 [get_ports {mic_data[10]}]
set_property PACKAGE_PIN J4 [get_ports {mic_data[9]}]
set_property PACKAGE_PIN E6 [get_ports {mic_data[8]}]
set_property PACKAGE_PIN H4 [get_ports {mic_data[7]}]
set_property PACKAGE_PIN H1 [get_ports {mic_data[6]}]
set_property PACKAGE_PIN G1 [get_ports {mic_data[5]}]
set_property PACKAGE_PIN G3 [get_ports {mic_data[4]}]
set_property PACKAGE_PIN H2 [get_ports {mic_data[3]}]
set_property PACKAGE_PIN G4 [get_ports {mic_data[2]}]
set_property PACKAGE_PIN G2 [get_ports {mic_data[1]}]
set_property PACKAGE_PIN F3 [get_ports {mic_data[0]}]
set_property PACKAGE_PIN H17 [get_ports mic_data_valid]





connect_debug_port u_ila_0/probe0 [get_nets [list {cic_out_data[0]} {cic_out_data[1]} {cic_out_data[2]} {cic_out_data[3]} {cic_out_data[4]} {cic_out_data[5]} {cic_out_data[6]} {cic_out_data[7]} {cic_out_data[8]} {cic_out_data[9]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list cic_out_valid]]
connect_debug_port u_ila_0/probe2 [get_nets [list m_clk_rising]]


set_property PACKAGE_PIN F5 [get_ports LR_sel]
set_property PACKAGE_PIN J5 [get_ports mic_clock]
set_property PACKAGE_PIN H5 [get_ports mic_data]
set_property PACKAGE_PIN B11 [get_ports H_sync]
set_property PACKAGE_PIN B12 [get_ports V_sync]
set_property IOSTANDARD LVCMOS33 [get_ports H_sync]
set_property IOSTANDARD LVCMOS33 [get_ports mic_clock]
set_property IOSTANDARD LVCMOS33 [get_ports mic_data]
set_property IOSTANDARD LVCMOS33 [get_ports V_sync]
set_property PACKAGE_PIN D8 [get_ports {Blue[3]}]
set_property PACKAGE_PIN D7 [get_ports {Blue[2]}]
set_property PACKAGE_PIN C7 [get_ports {Blue[1]}]
set_property PACKAGE_PIN B7 [get_ports {Blue[0]}]
set_property PACKAGE_PIN A6 [get_ports {Green[3]}]
set_property PACKAGE_PIN B6 [get_ports {Green[2]}]
set_property PACKAGE_PIN A5 [get_ports {Green[1]}]
set_property PACKAGE_PIN C6 [get_ports {Green[0]}]
set_property PACKAGE_PIN A4 [get_ports {Red[3]}]
set_property PACKAGE_PIN C5 [get_ports {Red[2]}]
set_property PACKAGE_PIN B4 [get_ports {Red[1]}]
set_property PACKAGE_PIN A3 [get_ports {Red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LR_sel]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[0]}]

connect_debug_port u_ila_0/clk [get_nets [list slow_clk_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {Mic/cic_out_data[0]} {Mic/cic_out_data[1]} {Mic/cic_out_data[2]} {Mic/cic_out_data[3]} {Mic/cic_out_data[4]} {Mic/cic_out_data[5]} {Mic/cic_out_data[6]} {Mic/cic_out_data[7]} {Mic/cic_out_data[8]} {Mic/cic_out_data[9]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list Mic/cic_out_valid]]
connect_debug_port dbg_hub/clk [get_nets slow_clk_BUFG]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 9 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ic/counter[0]} {ic/counter[1]} {ic/counter[2]} {ic/counter[3]} {ic/counter[4]} {ic/counter[5]} {ic/counter[6]} {ic/counter[7]} {ic/counter[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {data_out_mic[0]} {data_out_mic[1]} {data_out_mic[2]} {data_out_mic[3]} {data_out_mic[4]} {data_out_mic[5]} {data_out_mic[6]} {data_out_mic[7]} {data_out_mic[8]} {data_out_mic[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list Mic/m_clk_rising]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list start_fft]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list start_vga]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list valid_mic]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
